### ISSUE TITLE
Bug: "unable to retrieve automatically the package name and version"

### ISSUE THREAD

**Issue by selfagency** [adbayb/termost#21]
## Description

Getting the error:

```sh
error: Termost was unable to retrieve automatically the package name and version. To fix it, use `termost({ name, description, version })` to define them manually.
      at I (/$bunfs/root/exporter:21735:11)
      at Z (/$bunfs/root/exporter:21704:47)
      at /$bunfs/root/exporter:22507:15
```

But when I try to do that I get a TypeScript error and the same error above regardless:

![CleanShot 2024-02-24 at 16 32 14@2x](https://github.com/adbayb/termost/assets/2541728/62968e1e-18e4-422f-ba8f-2412b365b9b7)

## Reproduction

[Gist](https://gist.github.com/selfagency/bb28d2fd028a03e71ec707ff28bc19b0)

## Environment

Bun 1.0.28
Node 18.17.1

**Comment by adbayb** [comment]
@selfagency Your package metadata (including `name`, `description`, and `version`) needs to be put in the first argument. 
The second argument is for callbacks 👍 . 
The following change should work:

```ts
const program = termost<ProgramContext>(
	{
		name: "wpconv",
		description: "WordPress data converter",
		version: "0.0.1",
	},
	{
		onException(error) {
			log.error(error);
		},
		onShutdown() {
			log.info("Fin.");
		},
	},
);
```

Can you confirm it?

**Comment by adbayb** [comment]
Closed since not reproducible. 
@selfagency Feel free to re-open it if needed.
