### ISSUE TITLE
Default command.  

### ISSUE THREAD

**Issue by garronej** [adbayb/termost#28]
Hello @adbayb,

After conducting due diligence on the existing solutions, I've decided to go with termost. It looks great, and I'm considering using it for [keycloakify](https://keycloakify.dev).

However, I noticed that it lacks the ability to set a default command, similar to how `yarn` defaults to `yarn install`.

Is there a hook or a workaround for this that I might have missed?

Best regards,

**Comment by adbayb** [comment]
Hello again @garronej 👋 ,
Nice to hear you've chosen Termost for your project.

Empty command behavior has not been implemented yet. I'm considering more, as a default behavior, the one one from `pnpm` or `docker` CLI that displays the help output if no command is provided. 
But an option can also be considered to fall back to a default command 👍 . 

What do you think?

**Comment by garronej** [comment]
Hello @adbayb,  
Printing help would be very nice!  
I wanted a default option for retrocompatibility concerns but since ther's so many breaking changes in anyway I guess printing help is the better behavior.

**Comment by adbayb** [comment]
@garronej Implemented in the [latest version](https://github.com/adbayb/termost/releases/tag/termost%400.13.0) (v0.13) 👍 .
Feel free to reopen the issue if there are any issues.

**Comment by garronej** [comment]
Cool! Thank you!  
I'll let you know :)
